flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    mealType = StringField('Meal Type', validators=[DataRequired()])
    mainIngredient = StringField('Protein')
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/dishes/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post

dishes = Blueprint('dishes', __name__)



@dishes.route('/chicken')
def chicken():
    protein="Chicken"
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(mainIngredient=protein)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('dishes.html', posts=posts, protein=protein)

"""
    localhost:5000/about
    Contentless /about page for html templating for layouts.html extension
    and for easy copy pastring if future route additions
"""
@dishes.route('/top5')
def top5():
    topDishes=[30, 29, 18, 26, 17]
    #page = request.args.get('page', 1, type=int)
    post1 = Post.query.get_or_404(topDishes[0])
    post2 = Post.query.get_or_404(topDishes[1])
    post3 = Post.query.get_or_404(topDishes[2])
    post4 = Post.query.get_or_404(topDishes[3])
    post5 = Post.query.get_or_404(topDishes[4])

    return render_template('top5.html', post1=post1, post2=post2, post3=post3, post4=post4, post5=post5)

@dishes.route('/beef')
def beef():
    protein="Beef"
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(mainIngredient=protein)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('dishes.html', posts=posts, protein=protein)

@dishes.route('/dinner')
def dinner():
    mealType="Dinner"
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(mealType=mealType)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('mealType.html', posts=posts, mealType=mealType)

@dishes.route('/breakfast')
def breakfast():
    mealType="Breakfast"
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(mealType=mealType)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('mealType.html', posts=posts, mealType=mealType)



#enddishes

flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)

"""
    localhost:5000/    or    localhost:5000/home
    No get/post methods required

    default page = 1
    page = pageNumber from args.get()
        -> http://127.0.0.1:5000/home?page=2
           get all args after 'page' -> button clicks below posts
    posts = all posts on page = X, posts per_page = 3
        -> Sort all these posts by date_descending (newest posts first!)
"""
@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=3)
    return render_template('home.html', posts=posts)

"""
    localhost:5000/about
    Contentless /about page for html templating for layouts.html extension
    and for easy copy pastring if future route additions
"""
@main.route('/about')
def about():
    return render_template('about.html', title='About')


#endmain

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)

"""
    localhost:5000/post/new
    The form used on new posts in PostForm()
    If entire form is valid on submit:
        Fetch TITLE and CONTENT from form.data
        Post.author = current_user
            -> This is used for One-to-Many relationship between
               User and Posts -> One author can have many posts
        Save new post to database -> Then commit those changes
"""
@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm() #Object creation to act on the PostForm class
    if form.validate_on_submit():
        post = Post(title=form.title.data, mealType=form.mealType.data,
                    mainIngredient=form.mainIngredient.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                            form=form, legend='New Post')

"""
    localhost:5000/post/#
        where '#' is equal to the specific post_id
    grab a post by using -> query.get_or_404(post_id)
        where post_id is passed to post() function

    render this post using the post.html template, title=post.title
"""
@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

"""
    localhost:5000/post/#/update
        where '#' is equal to the specific post_id

        grab a post by using -> query.get_or_404(post_id)
        where post_id is passed to update_post() function

        Verifiy that current_user = post.author
            abort(403) -> Forbidden route -> HTTP response
        Use the PostForm() form from forms.py

        grab updated title and content from form.title/content.data
            Then commit these changes
        Flash a success message, then redirect the user to the updated post

    render this post using the creat_post.html template, title=Update Post
"""
@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403) #Forbidden route HTTP response -> Will customize later
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.mealType = form.mealType.data
        post.mainIngredient = form.mainIngredient.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.mealType.data = post.mealType
        form.mainIngredient.data = post.mainIngredient
        form.content.data = post.content
    """
        On GET request:
            autofill in form.title.data with post.title
            autofill in form.content.data with post.content
    """
    return render_template('create_post.html', title='Update Post',
                            form=form, legend='Update Post')


"""
    localhost:5000/post/#/delete
        where '#' is equal to the specific post_id

        grab a post by using -> query.get_or_404(post_id)
        where post_id is passed to delete_post() function

        Verifiy that current_user = post.author
            abort(403) -> Forbidden route -> HTTP response

        db.session.delete(post) -> db.session.commit()
        flash confirmation message for successful deletion
        redirect user to home page
"""
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)

"""
    localhost:5000/register
    Accepts GET and POST methods
"""
@users.route('/register', methods=['GET', 'POST'])
def register():
    #Once user is_authenticated -> redirect to home using url_for
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    """
        Use RegistrationForm() -> Accepts:
            form.password.data
                bcrypt.generate_password with 128bit hash encryption
                decode with utf-8 to remove b' xxxxxxxxxxxx ' from password
    """
    if form.validate_on_submit(): #Flash a message after created account
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to login!', 'success')#LOOK UP
        return redirect(url_for('users.login'))#function name for def home(): ^^
    return render_template('register.html', title='Register', form=form)

"""
    localhost:5000/login
    Accepts GET and POST methods
"""
@users.route('/login', methods=['GET','POST'])
def login():
    #Once user is_authenticated -> redirect to home using url_for
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    """
        Accepts email(stringField), password(passField), amd remember(bool)
        Remember Me: WORK ON THIS -> Populate form.email.data with current_user Email
        Must validate and prove current user with browser token?
    """
    if form.validate_on_submit():
        #Query filter_by first email match -> then set user var to entire User data struct
        user = User.query.filter_by(email=form.email.data).first()
        #if user is populated, that means user email exists.
        #Then use bcrypt.check_password_hash to check if form.data matches user.password
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            #Log them in when validated
            login_user(user, remember=form.remember.data)
            """
                if redirected here from @login_required pages
                ->  Track ?next=xxxxxxx and store it in next_page var
                    Take next_page and use it in ternary single line
            """
            next_page = request.args.get('next')
            """
                Use args.get() instead of args[] like an array
                args[] will throw error if no next key
                args.get() will return 'none' if no next key
            """
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
            #ternary (do -> if true, else -> so something else)
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
            #Flash message for unsuccessful -> Do not reveal is user/pass is wrong.
    return render_template('login.html', title='Login', form=form)



"""
    localhost:5000/logout
    simple logout method
    sent here on logout button press
"""
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))



"""
    localhost:5000/account
    The account function provides the support to change account info.
    The account info that can be changed is: username, email, and profile pic
    TODO -> Add ability to reset password
            Change password
            Change email linked to account.
"""
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    """
        Show ^UpdateAccountForm()^
        Once form is validated:
            resize and save picture if form.picture.data is populated
            current_user name and email = form.name/email.data
                This is simply way to update data in database
            flash confirmation message stating successful info update
    """
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    """
        On GET request:
            autofill in form.username.data with current_user.username
            autofill in form.email.data with current_user.email
        Display the current profile pic by fetching picture from:
            static/profile_pics/+ current_user.Image_file
                -> This will always display most updated image
    """
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)



"""
    localhost:5000/user/string
        where 'string' is the username of the specific user

        set default page to page 1 and the pages are of type int
        find first user using username passed to user_posts() function

        query for all posts by user
            ordered by date_descending and
            paginate 5 posts per page
"""
@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)



@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))

    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    #This will receive the user_id if it matches the token
    user = User.verify_reset_token(token)
    if user is None:
        flash('This is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit(): #Flash a message after created account
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to login', 'success')#LOOK UP
        return redirect(url_for('users.login'))#function name for def home(): ^^
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layouts.html" %}
{% block content %}
    <h1>About Page<h1>
{% endblock content %}

flaskblog/templates/dishes.html
{% extends "layouts.html" %}
{% block content %}
  {% if protein == 'Top 5' %}
  <h1 class="mb-3">{{ protein }} Dishes of All Time!</h1>
  {% else %}
  <h1 class="mb-3">Dishes with {{ protein }} ({{ posts.total }})</h1>
  {% endif %}
{% for post in posts.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <small class="text-muted"> &nbsp;{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          <small class="text-muted"> &emsp;&nbsp; Tags:</small>
          <b><small class="text-muted">{{ post.mealType }}</small></b>
          <b><small class="text-muted">{{ post.mainIngredient }}</small></b>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    </article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
      <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
    {% else %}
      <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
    {% endif %}
  {% else %}
    ...
  {% endif %}
{% endfor %}
{% endblock content %}

flaskblog/templates/home.html
{% extends "layouts.html" %}
{% block content %}
{% for post in posts.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <small class="text-muted"> &nbsp;{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          <small class="text-muted"> &emsp;&nbsp; Tags:</small>
          <b><small class="text-muted">{{ post.mealType }}</small></b>
          <b><small class="text-muted">{{ post.mainIngredient }}</small></b>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    </article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
      <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
    {% else %}
      <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
    {% endif %}
  {% else %}
    ...
  {% endif %}
{% endfor %}
{% endblock content %}

flaskblog/templates/layouts.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">

    {% if title %}
      <title>Recipe Memory - {{ title }}</title>
    {% else %}
      <title>Recipe Memory</title>
    {% endif %}
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Recipe Memory</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Quick Links</h3>
            <p class='text-muted'>Click below for more dishes.
              <ul class="list-group">
                <a class="list-group-item list-group-item-light" href="{{ url_for('dishes.top5') }}">Top 5 Dishes</a>
                <a class="list-group-item list-group-item-light" href="{{ url_for('dishes.chicken') }}">Chicken Dishes</a>
                <a class="list-group-item list-group-item-light" href="{{ url_for('dishes.beef') }}">Beef Dishes</a>
                <a class="list-group-item list-group-item-light" href="{{ url_for('dishes.dinner') }}">Dinner</a>
                <a class="list-group-item list-group-item-light" href="{{ url_for('dishes.breakfast') }}">Breakfast</a>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

flaskblog/templates/login.html
{% extends "layouts.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/mealType.html
{% extends "layouts.html" %}
{% block content %}
<h1 class="mb-3">{{ mealType }} Dishes ({{ posts.total }})</h1>
{% for post in posts.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <small class="text-muted"> &nbsp;{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          <small class="text-muted"> &emsp;&nbsp; Tags:</small>
          <b><small class="text-muted">{{ post.mealType }}</small></b>
          <b><small class="text-muted">{{ post.mainIngredient }}</small></b>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    </article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
      <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
    {% else %}
      <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
    {% endif %}
  {% else %}
    ...
  {% endif %}
{% endfor %}
{% endblock content %}

flaskblog/templates/post.html
{% extends "layouts.html" %}
{% block content %}
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
      <small class="text-muted"> &nbsp;{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
      <small class="text-muted"> &emsp;&nbsp; Tags:</small>
      <b><small class="text-muted">{{ post.mealType }}</small></b>
      <b><small class="text-muted">{{ post.mainIngredient }}</small></b>
      {% if post.author == current_user %}
        <div>
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
          <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layouts.html" %}
{% block content %}
  <h1 class="mb-3">Posts by {{ user.username}} ({{ posts.total }})</h1>
  {% for post in posts.items %}
      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <small class="text-muted"> &nbsp;{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          <small class="text-muted"> &emsp;&nbsp; Tags:</small>
          <b><small class="text-muted">{{ post.mealType }}</small></b>
          <b><small class="text-muted">{{ post.mainIngredient }}</small></b>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
      </article>
  {% endfor %}
  {% for page_num in posts.iter_pages(left_edge=2, right_edge=2, left_current=2, right_current=3) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
{% endblock content %}